actions_list = {
    "saved_appliances": [
        "saved_appliances_list",
        "duplicate_appliance",
        "saved_appliance_edit",
        "appliance_not_available",
        "deleting_saved_appliance",
        "adding_saved_appliance",
        "saved_appliances_error"
    ],
    "renewable_data":[
      "renewable_data_list",
      "renewable_data_error",
    ],
    "scheduledappliances":[
      "schedule_appliances_empty",
      "create_multiple_schedules",
      "schedule_appliances_list",
      "schedule_appliances_add",
      "schedule_appliances_delete",
      "schedule_appliances_edit",
      "schedule_appliances_error",
    ],
    "userusage":[
      "user_usage_data",
      "user_usage_error",
    ],
    "recommendations":[
      "recommendations_data",
      "recommendations_empty",
      "recommendations_error",
    ],
    "weeklyconsumptionpredicted":[
      "weekly_consumption_predicted_list",
      "weekly_consumption_predicted_error",
    ],
    "liveprice":[
      "live_price_data",
      "live_price_error",
    ],
    "priceprediction":[
      "price_prediction_data",
      "price_prediction_error",
    ],
    "allowedAppliances":[
      "allowedAppliances_data",
      "allowedAppliances_error",
      "not_found_in_allowed_appliances",
    ],
    "general":[
      "answer",
      "error",
      "insufficient_information",
      "unknown",
    ]
}