export type ApplianceType =
  | "Vehicle"
  | "Laundry"
  | "Kitchen"
  | "Heating"
  | "Cooling"
  | "Energy Storage"
  | "Water"
  | "Air";
export const Availableappliances = [
  {
    id: "ev-charger",
    name: "EV Charger",
    dbName: "evcharger",
    category: "High Consumption",
    applianceType: "Vehicle",
    isReplacable: false,
    time: "100",
  },
  {
    id: "washing-machine",
    name: "Washing Machine",
    dbName: "washingmachine",
    category: "Flexible",
    applianceType: "Laundry",
    isReplacable: false,
    time: "100",
  },
  {
    id: "dishwasher",
    name: "Dishwasher",
    dbName: "dishwasher",
    category: "Flexible",
    applianceType: "Kitchen",
    isReplacable: false,
    time: "100",
  },
  {
    id: "tumble-dryer",
    name: "Tumble Dryer",
    dbName: "tumbledryer",
    category: "Flexible",
    applianceType: "Laundry",
    isReplacable: true,
    time: "100",
  },
  {
    id: "electric-water-heater",
    name: "Electric Water Heater",
    dbName: "electricwaterheater",
    category: "High Consumption",
    applianceType: "Heating",
    isReplacable: false,
  },
  {
    id: "heat-pump",
    name: "Heat Pump",
    dbName: "heatpump",
    category: "High Consumption",
    applianceType: "Heating",
    isReplacable: false,
  },
  {
    id: "air-conditioner",
    name: "Air Conditioner",
    dbName: "airconditioner",
    category: "High Consumption",
    applianceType: "Cooling",
    isReplacable: true,
  },
  {
    id: "home-battery-storage",
    name: "Home Battery Storage",
    dbName: "homebatterystorage",
    category: "Energy Storage",
    applianceType: "Energy Storage",
    isReplacable: false,
  },
  {
    id: "electric-floor-heating",
    name: "Electric Floor Heating",
    dbName: "electricfloorheating",
    category: "High Consumption",
    applianceType: "Heating",
    isReplacable: false,
  },
  {
    id: "chest-freezer",
    name: "Chest Freezer",
    dbName: "chestfreezer",
    category: "Continuous Usage",
    applianceType: "Kitchen",
    isReplacable: false,
  },
  {
    id: "pool-pump",
    name: "Pool Pump",
    dbName: "poolpump",
    category: "Flexible",
    applianceType: "Water",
    isReplacable: true,
  },
  {
    id: "electric-oven",
    name: "Electric Oven",
    dbName: "electricoven",
    category: "Moderate Consumption",
    applianceType: "Kitchen",
    isReplacable: true,
  },
  {
    id: "clothes-iron",
    name: "Clothes Iron",
    dbName: "clothesiron",
    category: "Moderate Consumption",
    applianceType: "Laundry",
    isReplacable: true,
  },
  {
    id: "dehumidifier",
    name: "Dehumidifier",
    dbName: "dehumidifier",
    category: "Moderate Consumption",
    applianceType: "Air",
    isReplacable: true,
  },
  {
    id: "air-purifier",
    name: "Air Purifier",
    dbName: "airpurifier",
    category: "Continuous Usage",
    applianceType: "Air",
    isReplacable: true,
  },
  {
    id: "sauna-heater",
    name: "Sauna Heater",
    dbName: "saunaheater",
    category: "High Consumption",
    applianceType: "Heating",
    isReplacable: true,
  },
  {
    id: "space-heater",
    name: "Space Heater",
    dbName: "spaceheater",
    category: "High Consumption",
    applianceType: "Heating",
    isReplacable: true,
  },
  {
    id: "electric-boiler",
    name: "Electric Boiler",
    dbName: "electricboiler",
    category: "High Consumption",
    applianceType: "Heating",
    isReplacable: false,
  },
  {
    id: "water-pump",
    name: "Water Pump",
    dbName: "waterpump",
    category: "Moderate Consumption",
    applianceType: "Water",
    isReplacable: false,
  },
];

export const ApplianceNames = [
  "EV Charger",
  "Washing Machine",
  "Dishwasher",
  "Tumble Dryer",
  "Electric Water Heater",
  "Heat Pump",
  "Air Conditioner",
  "Home Battery Storage",
  "Electric Floor Heating",
  "Chest Freezer",
  "Pool Pump",
  "Electric Oven",
  "Clothes Iron",
  "Dehumidifier",
  "Air Purifier",
  "Sauna Heater",
  "Space Heater",
  "Electric Boiler",
  "Water Pump",
];
